# Generated by Django 5.2.1 on 2025-05-21 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id_plano', models.AutoField(primary_key=True, serialize=False)),
                ('nome_plano', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=20)),
            ],
            options={
                'db_table': 'Plano',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor')], max_length=50)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id_treino', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('pendente', 'Pendente')], max_length=20)),
                ('nome_treino', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('id_plano', models.ForeignKey(db_column='id_plano', on_delete=django.db.models.deletion.CASCADE, to='api_rest.plano')),
            ],
            options={
                'db_table': 'Treino',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id_avaliacao', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.SmallIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_avaliacao', models.DateField(auto_now_add=True)),
                ('id_treino', models.ForeignKey(db_column='id_treino', on_delete=django.db.models.deletion.CASCADE, to='api_rest.treino')),
            ],
            options={
                'db_table': 'Avaliacao',
            },
        ),
        migrations.AddField(
            model_name='plano',
            name='id_aluno',
            field=models.ForeignKey(db_column='id_aluno', on_delete=django.db.models.deletion.CASCADE, to='api_rest.usuario'),
        ),
        migrations.CreateModel(
            name='Desempenho',
            fields=[
                ('id_desempenho', models.AutoField(primary_key=True, serialize=False)),
                ('indicador', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('id_aluno', models.ForeignKey(db_column='id_aluno', on_delete=django.db.models.deletion.CASCADE, to='api_rest.usuario')),
            ],
            options={
                'db_table': 'Desempenho',
            },
        ),
    ]
